version: '3.9'

services:
  buttermap:
    image: node:18
    container_name: buttermap
    working_dir: /usr/src/app
    volumes:
      - ./buttermap-ui:/usr/src/app
      - ./map changes:/map changes
      - /usr/src/app/node_modules
    ports:
      - "3000:3000" # Map port 3000 of the container to port 3000 on the host
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      PORT: 3000
      CHOKIDAR_USEPOLLING: "true" # Ensure hot reload works inside Docker
