import {createSlice, PayloadAction} from '@reduxjs/toolkit';
import type {AppDispatch} from './buttermapStore';
import {TypedUseSelectorHook, useDispatch, useSelector} from 'react-redux';

import {ButtermapState, initialMapState} from "@/app/redux/buttermapState";

import {MapMode} from "@/app/model/common";
import {CoordinateChange, FullCoordinate, SimpleCoordinate} from "@/app/model/coordinate";
import {ChangeFile} from "@/app/views/coordinateChangesList";
import {RouteResult} from "@/app/map/route";


export type SetValuePayload = {
    name: string
    value: any
}

export const useAppDispatch: () => AppDispatch = useDispatch;
export const useAppSelector: TypedUseSelectorHook<ButtermapState> = useSelector;


// Create a slice of state

const buttermapStateSlice = createSlice({
    name: 'buttermap',
    initialState: initialMapState,
    reducers: {
        setUse3D: (state: ButtermapState, action: PayloadAction<boolean>) => {
            state.settings.use3D = action.payload;
        },
        setAvoidWater: (state: ButtermapState, action: PayloadAction<boolean>) => {
            state.settings.avoidWater = action.payload;
        },
        setMode: (state: ButtermapState, action: PayloadAction<MapMode>) => {
            state.settings.mapMode = action.payload;
        },
        setHighlightedCoords: (state: ButtermapState, action: PayloadAction<SimpleCoordinate[]>) => {
            state.highlightedCoords = action.payload;
        },
        setEditModalOpen: (state: ButtermapState, action: PayloadAction<boolean>) => {
            state.editModalOpen = action.payload;
        },
        setViewModalOpen: (state: ButtermapState, action: PayloadAction<boolean>) => {
            state.viewModalOpen = action.payload;
        },
        setChanges: (state: ButtermapState, action: PayloadAction<CoordinateChange[]>) => {
            state.changes = action.payload;
        },
        setActiveChange: (state: ButtermapState, action: PayloadAction<ChangeFile | null>) => {
            state.activeChange = action.payload;
        },
        setActiveRoute: (state: ButtermapState, action: PayloadAction<RouteResult | null>) => {
            state.activeRoute = action.payload;
        },
        setActiveCoordinate: (state: ButtermapState, action: PayloadAction<FullCoordinate | null>) => {
            state.activeCoordinate = action.payload;
        },
        resetState: (state: ButtermapState, action: PayloadAction<void>) => {
            return initialMapState
        },
    }
});

// Export actions generated by createSlice
export const {
    setUse3D,
    setAvoidWater,
    setMode,
    setHighlightedCoords,
    setEditModalOpen,
    setViewModalOpen,
    setChanges,
    setActiveChange,
    setActiveRoute,
    setActiveCoordinate,
    resetState
} = buttermapStateSlice.actions;


// Export the reducer to be used in the store configuration
export default buttermapStateSlice.reducer;
